import {ReactNode} from 'react'
import '../styles/tailwind.css'
import Header from '../container/header/Header'

export const metadata = {
  title: 'Posts',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang='en '>
      <body className={'bg-pageBg '}>
        <div className={'max-w-[1600px] h-full w-full mx-auto'}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
