import {ReactNode} from 'react'
import '../styles/tailwind.css'
import Header from '../container/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang='ko min-h-screen min-w-screen'>
      <body className={'bg-pageBg min-h-screen min-w-screen'}>
        <div className={'max-w-lg'}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
