import React, {ReactNode} from 'react'
import '../styles/tailwind.css'
import Header from '../container/header/Header'
import NextAuthProviders from '../components/providers/NextAuthProviders'

export const metadata = {
  title: 'Posts',
  description: 'Generated by create next app',
}

const RootLayout = ({children}: {children: ReactNode}) => {
  return (
    <html lang='en '>
      <body className={'bg-pageBg '}>
        <NextAuthProviders>
          <div className={'max-w-[1600px] h-full w-full mx-auto'}>
            <Header />
            {children}
          </div>
        </NextAuthProviders>
      </body>
    </html>
  )
}
export default RootLayout
